title: Baja Divide
description: A blog for route info and updates

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

url: "https://phatboyle.github.io"
baseurl: "/bajadivide"

# Optional minima settings
minima:
  skin: auto
  date_format: "%b %d, %Y"

# Show specific pages in header nav
header_pages:
  - about.md
